name: Deploy React App

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Raspberry

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v2

    # Étape 2 : Configuration de Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4 : Builder l'application React
    - name: Build React app
      run: npm run build

    - name: Debug SSH host and user
      run: |
        echo "SSH Host: ${{ secrets.SSH_HOST }}"
        echo "SSH User: ${{ secrets.SSH_USER }}"
        echo "SSH Mdp : ${{ secrets.SSH_PASSWORD }}"
        
    # Étape 5 : Transférer les fichiers vers le serveur via SSH (avec mot de passe)
    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: 'dist/'
        target: '/var/www/html/Cube-Front'

    # Étape 6 : Redémarrer le serveur Apache (si nécessaire)
    - name: Restart Apache server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: sudo systemctl restart apache2
