name: Deploy React App

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Raspberry 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t web-front .

      - name: Save Docker image as a tar file
        run: docker save -o web-front.tar web-front

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-image
          path: web-front.tar

  deploy-on-server:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: build-image
          path: web-front.tar

      - name: Transfer Docker image via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: web-front.tar
          target: "/var/www/html/Cube-Front"

      - name: Load Docker image on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/Cube-Front/
            docker load -i web-front.tar

      - name: Run Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run -d --name web-front-container -p 80:80 web-front
