name: Build and deploy
on:
push:
branches: develop

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    -name: Set up Node.js
    use: actions/setup-node@latest
    with:
    node-version: "18"

    -name: install dependencies
    run: npm install



